[server]
maxUploadSize = 1500
address = "127.0.0.1"
port = 10087
baseUrlPath = "psbenchmarkwebsite"
headless = true

[browser]
gatherUsageStats = false
serverAddress = "lab.ybh1998.space"

[logger]
level = "debug"
